services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: "webcis-api:prod"
    container_name: webcis-api-prod
    ports:
      - "82:80"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    working_dir: /var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - webcis
    healthcheck:
      test: [ "CMD", "php", "-v" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s


  queue:
    image: "webcis-api:prod"
    container_name: webcis-queue-prod
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - webcis

  mariadb:
    image: mariadb:11
    container_name: webcis-mariadb-prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data_prod:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - webcis
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p$MARIADB_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s


  mailpit:
    image: axllent/mailpit
    container_name: webcis-mailpit-prod
    restart: unless-stopped
    ports:
      - "8027:8025"
      - "1027:1025"
    networks:
      - webcis

volumes:
  mariadb_data_prod:

networks:
  webcis:
